### ISSUE TITLE
get_l10n_strings.py must not create `google_play_strings.json` when it fails to contact the website

### ISSUE THREAD

**Issue by JohanLorenzo** [mozilla-releng/mozapkpublisher#188]
Today, there was a bustage of the l10n community website. It did make the task fail: https://tools.taskcluster.net/groups/DVYoGBtFSxGmu9HO6DjRcA/tasks/ZKje9f9uTZSZc70N5Zf3MA/runs/1/logs/public%2Flogs%2Flive_backing.log

``` py
[taskcluster 2019-04-18 10:24:20.955Z] === Task Starting ===
+ python3 ./mozapkpublisher/get_l10n_strings.py --package-name org.mozilla.fennec_aurora --output-file /builds/worker/google_play_strings.json
2019-04-18 10:24:21,478 - connectionpool.py - DEBUG - Starting new HTTPS connection (1): l10n.mozilla-community.org:443
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.6/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]
```

That said, the `public/google_play_strings.json` was uploaded (as an empty file). It made the push-apk task download this fail, but failed to interpret it: https://tools.taskcluster.net/groups/DVYoGBtFSxGmu9HO6DjRcA/tasks/YHlj9BaGQnuWeHpVzUjLcA/runs/1/logs/public%2Flogs%2Flive_backing.log#L35

```py
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is real problem because the push-apk task cannot upload the APKs. That's not the behavior we intended when [bug 1385401](https://bugzil.la/1385401) was done.

**Comment by jcristau** [comment]
get_l10n_strings.py was removed back in #224.
