### ISSUE TITLE
--latest-nightly fails to get the checksum

### ISSUE THREAD

**Issue by sylvestre** [mozilla-releng/mozapkpublisher#65]
{{{
2018-06-17 19:55:00,683 - connectionpool.py - DEBUG - Starting new HTTPS connection (1): ftp.mozilla.org
2018-06-17 19:55:00,955 - connectionpool.py - DEBUG - https://ftp.mozilla.org:443 "GET /pub/mobile/candidates/62.0a1-candidates/build1/SHA512SUMS HTTP/1.1" 404 309
Traceback (most recent call last):
  File "mozapkpublisher/get_apk.py", line 217, in <module>
    myScript.run()
  File "mozapkpublisher/get_apk.py", line 118, in run
    self.download_all(version, build, locale)
  File "mozapkpublisher/get_apk.py", line 108, in download_all
    self.download(version, build, architecture, locale)
  File "mozapkpublisher/get_apk.py", line 94, in download
    download_file(checksums['url'], checksums['download_location'])
  File "/home/sylvestre/dev/mozilla/mozapkpublisher/mozapkpublisher/common/utils.py", line 12, in download_file
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://ftp.mozilla.org/pub/mobile/candidates/62.0a1-candidates/build1/SHA512SUMS
}}}

**Comment by JohanLorenzo** [comment]
`/pub/mobile/candidates/62.0a1-candidates/build1/SHA512SUMS` isn't valid for nightly. There's a bug in mozapkpublihser (a fallout of #58), but we're also missing checksums on https://archive.mozilla.org/pub/mobile/nightly/latest-mozilla-central-android-api-16/ since 60. I'll file a bug for that

**Comment by JohanLorenzo** [comment]
Per [bug 1469303 comment 3](https://bugzilla.mozilla.org/show_bug.cgi?id=1469303#c3), `mozapkpublisher` can fetch the checksums under the `en-US` folder. It's not ideal, but this fixes this issue, for sure.
